//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by backup.rc
//
#define MENU_PATHCONVERT                0
#define IDR_RT_MANIFEST1                1
#define DELNOT_ABORT                    3
#define DELNOT_YESALL                   4
#define DELNOT_NOALL                    5
#define backup                          101
#define main_menu                       102
#define main_dlg                        103
#define list_bmp                        104
#define transfer_dlg                    105
#define job_add_dlg                     106
#define job_del_dlg                     107
#define tr_notify_dlg                   108
#define about_dlg                       109
#define bmain_dlg                       110
#define patset_name_dlg                 111
#define backup_tiny_1                   112
#define backup_tiny_2                   113
#define backup_tiny_3                   114
#define backup_tiny_4                   115
#define backup_tiny_5                   116
#define backup_tiny_6                   117
#define backup_tiny_7                   118
#define backup_tiny_8                   119
#define backup_tiny_9                   120
#define backup_tiny_a                   121
#define dummy                           122
#define backup_tiny_b                   123
#define del_notify_dlg                  124
#define inpfile_folder_dlg              125
#define dragdrop_err_dlg                126
#define grip_icon                       127
#define notify_icon                     128
#define quick_dlg                       129
#define del_pat_notify_dlg              130
#define IDC_CURSOR1                     131
#define PATSET_QUIT                     132
#define MENU_DISPLOG                    133
#define ID_138                          134
#define patset_frame_dlg                135
#define notify2_icon                    136
#define IDD_DIALOG1                     137
#define path_convert_ign_dlg            138
#define MENU_HELP_QA                    139
#define reginit_dlg                     140
#define MENU_SORT                       141
#define MENU_SORT2                      142
#define shutdown_err_dlg                143
#define show_comment_dlg                144
#define IDD_DIALOG2                     145
#define common_msg_dlg                  146
#define IDD_DIALOG3                     147
#define quit_notify_dlg                 148
#define box_bmp                         149
#define current_bmp                     150
#define done_bmp                        151
#define MAIN_SRC                        1000
#define NOBACK_DIR                      1001
#define TRANS_DIRLIST                   1002
#define NOBACK_FILE                     1003
#define TRANS_EXEC                      1004
#define IDC_RADIO1                      1005
#define TRANS_SYNC                      1006
#define TRANS_RMDIR                     1007
#define LOG_NEW                         1008
#define MISC_COMMENT_NO                 1009
#define IDC_RADIO2                      1010
#define TRANS_DEL                       1011
#define TRANS_RMFILE                    1012
#define LOG_APPEND                      1013
#define MISC_COMMENT_TIP                1014
#define IDC_RADIO3                      1015
#define MAIN_START                      1016
#define TRANS_COPY                      1017
#define LOG_NOLIMIT                     1018
#define MISC_COMMENT_WIN                1019
#define MAIN_EXIT                       1020
#define TRANS_SCAN                      1021
#define MAIN_START2                     1022
#define TRANS_PREPARE                   1022
#define MAIN_ALLSTART                   1023
#define TRANS_STOP                      1024
#define MAIN_ADD                        1025
#define TRANS_SCAN2                     1026
#define TRANS_MKDIR                     1027
#define MAIN_DEL                        1028
#define MAIN_EDIT                       1029
#define MAIN_SET                        1030
#define MAIN_ALLCOPY                    1031
#define MAIN_FORCECOPY                  1032
#define MAIN_DELFILE                    1033
#define MAIN_DELDIR                     1034
#define MAIN_VOIDERR                    1035
#define JOB_SRC                         1036
#define JOB_SRC_BRO                     1037
#define JOB_DST                         1038
#define psh15                           0x040e
#define MAIN_DST_BR                     1039
#define JOB_DST_BRO                     1040
#define chx1                            0x0410
#define TRNOT_SRC                       1041
#define TRNOT_DST                       1042
#define IDC_ANIMATE1                    1043
#define TRNOT_VOL                       1044
#define MAIN_DST                        1045
#define MAIN_SRC_BR                     1046
#define TRANS_SRC                       1047
#define IDC_BUTTON1                     1048
#define LOG_FNAME_INIT                  1048
#define TRANS_LOGWRITE                  1049
#define BMAIN_EDIT                      1050
#define PATSET_ADD                      1051
#define TRNOT_NEXT                      1052
#define LOG_FNAME_BR                    1053
#define INPFILE_FILE_BR                 1054
#define QUICK_SIZE                      1055
#define PATSET_SOUNDFILE_BR             1056
#define PATSET_ADV_RESET                1057
#define PATSET_LABEL_GET                1058
#define TRANS_RETURN                    1059
#define MAIN_QUIT                       1060
#define TRANS_DST                       1061
#define IDC_LIST1                       1062
#define MAIN_JOBJOB                     1063
#define BMAIN_LIST                      1064
#define MAIN_LIST                       1065
#define PATSET_SRCLIST                  1066
#define TRNOT_SRCLIST                   1067
#define LOG_VIEWER_BR                   1068
#define IDC_EDIT1                       1069
#define PATSET_SRC                      1070
#define TRNOT_PREV                      1071
#define LOG_FNAME                       1072
#define TIMER_INT_TIME                  1073
#define INPFILE_FNAME                   1074
#define PATSET_EDIT                     1075
#define PATSET_LABEL                    1076
#define PATSET_COMMENT                  1077
#define MAIN_COMMENT                    1078
#define resize_ud_csr                   1079
#define PATSET_SOUNDFILE                1080
#define PATHCNV_FROM                    1081
#define SHUTDOWN_MSG                    1082
#define DLG_MSG                         1083
#define SHOWCOM_TEXT                    1084
#define NOBACK_BIG_SIZE                 1085
#define PATSET_TOLERANCE                1087
#define LOG_VIEWER                      1088
#define stc1                            0x0440
#define PATHCNV_FROM2                   1089
#define stc2                            0x0441
#define PATHCNV_TO                      1090
#define stc3                            0x0442
#define PATSET_ADD2                     1091
#define stc4                            0x0443
#define BMAIN_START                     1092
#define PATSET_EDIT2                    1093
#define BMAIN_NEW                       1094
#define MAIN_NEW                        1095
#define BMAIN_COPY                      1096
#define MAIN_COPY                       1097
#define BMAIN_DEL                       1098
#define MAIN_SIZE                       1099
#define BMAIN_UP                        1100
#define MAIN_UP                         1101
#define BMAIN_DOWN                      1102
#define MAIN_DOWN                       1103
#define BMAIN_END                       1104
#define MAIN_END                        1105
#define PATSET_DEL                      1106
#define PATSET_FORCE                    1107
#define PATSET_SORT                     1108
#define PATSET_RMDIR                    1109
#define PATSET_RMFILE                   1110
#define PATSET_NOERROR                  1111
#define PATSET_DST_BR                   1112
#define PATSET_NOTIFY_DEL               1113
#define PATSET_SRC_BR                   1114
#define PATSET_IGNNODEL                 1115
#define PATSET_NOTIFY_DEL2              1116
#define PATSET_NAME                     1117
#define NOBACK_FILE_BR                  1118
#define PATSET_NEWONLY                  1119
#define NOBACK_DIR_BR                   1120
#define lst1                            0x0460
#define PATSET_USE_TRASHCAN             1121
#define lst2                            0x0461
#define TRANS_PATNAME                   1122
#define PATSET_IGNATTR                  1123
#define LOG_SWITCH                      1124
#define PATSET_NOTIFY_OVERWRITE         1125
#define TIMER_INT_SW                    1126
#define LOG_UNICODE                     1127
#define TIMER_INT_TIME_SPN              1128
#define MISC_SAVEPOS                    1129
#define LOG_LIMIT                       1130
#define MISC_ESC_EXIT                   1131
#define LOG_LIMIT_SIZE                  1132
#define MISC_TRAYICON                   1133
#define MISC_REGTYPE                    1134
#define IDC_BUTTON2                     1135
#define PATSET_SIZE                     1136
#define cmb1                            0x0470
#define INPFILE_FOLDER_BR               1137
#define cmb2                            0x0471
#define QUICK_DST_BR                    1138
#define PATSET_SOUND_TEST               1139
#define PATSET_TOOLMENU                 1140
#define TRANS_QUIT                      1141
#define FSIZE_SRCLIST                   1142
#define NOBACK_FILE_TOOLMENU            1143
#define FSIZE_FILES                     1144
#define FSIZE_FOLDERS                   1145
#define FSIZE_SIZE                      1146
#define FSIZE_MESSAGE                   1147
#define DELNOT_FNAME                    1148
#define DELNOT_SRC_TIME                 1149
#define TRANS_PROGRESS                  1150
#define DELNOT_DST_TIME                 1151
#define PATSET_WAIT                     1152
#define edt1                            0x0480
#define DELNOT_SRC_SIZE                 1153
#define DLG_MSG1                        1154
#define DELNOT_DST_SIZE                 1155
#define MAIN_LINE_2                     1156
#define MAIN_LINE_1                     1157
#define TRANS_TITLE2                    1158
#define TRANS_BOX1                      1159
#define TRANS_LINE1                     1160
#define MAIN_GRIP                       1161
#define TRANS_GRIP                      1162
#define PATSET_CHK_LABEL                1163
#define QUICK_DST                       1164
#define QUICK_SRC                       1165
#define QUICK_SRC_BR                    1166
#define MAIN_SEPA                       1167
#define TRNOT_SHUTDOWN                  1168
#define TRNOT_QUIT                      1169
#define TRNOT_GRIP                      1170
#define TRNOT_MSG1                      1171
#define TRNOT_MSG2                      1172
#define TRNOT_MSG3                      1173
#define PATSET_SHUTDOWN                 1174
#define TRNOT_MSG4                      1175
#define CDOWN_MSG                       1176
#define TRNOT_SYSTEM                    1177
#define PATSET_SYSTEM                   1178
#define NOBACK_DIR_LIST                 1179
#define CDOWN_MSG2                      1180
#define NOBACK_DIR_ADD                  1181
#define NOBACK_DIR_DEL                  1182
#define NOBACK_FILE_LIST                1183
#define NOBACK_FILE_ADD                 1184
#define NOBACK_FILE_DEL                 1185
#define NOBACK_DIR_EDIT                 1186
#define NOBACK_FILE_EDIT                1187
#define NOBACK_DIR_SORT                 1188
#define NOBACK_FILE_SORT                1189
#define NOBACK_SYSTEM_FILE              1190
#define IDC_CHECK2                      1191
#define NOBACK_HIDDEN_FILE              1192
#define PATSET_SOUND                    1193
#define PATSET_TIMER_INT_SW             1194
#define PATSET_TIMER_INT_TIME           1195
#define PATSET_TIMER_INT_TIME_SPN       1196
#define PATSET_TREE                     1197
#define PATSET_DIALOG_POS               1198
#define PATSET_TOLERANCE_SPN            1199
#define PATSET_NO_DSTDIR                1200
#define PATSET_IGNTIME                  1201
#define PATSET_UP                       1202
#define PATSET_DOWN                     1203
#define NOBACK_DIR_TOOLMENU             1204
#define NOBACK_DIR_DOWN                 1205
#define NOBACK_DIR_UP                   1206
#define NOBACK_FILE_UP                  1207
#define IDC_CHECK1                      1208
#define PATSET_SHOW_COMMENT             1209
#define NOBACK_SIZE_FLG                 1210
#define NOBACK_BIG_FILE                 1211
#define NOBACK_FILE_DOWN                1212
#define DELNOT_MESSAGE                  1213
#define TRANS_PIC_SCAN                  1214
#define TRANS_PIC_RMDIR                 1215
#define PATSET_DSTLIST                  1216
#define TRANS_PIC_PREPARE               1216
#define TRANS_PIC_RMFILE                1217
#define TRANS_PIC_MKDIR                 1218
#define TRANS_PIC_MKDIR2                1219
#define TRANS_PIC_COPY                  1220
#define MAIN_SIZEGRIP                   1221
#define job_dlg                         1223
#define btransfer_dlg                   1224
#define patset_dir_dlg                  1225
#define patset_flg_dlg                  1226
#define patset_ign_dlg                  1227
#define patset_ign1_dlg                 1228
#define opt_log_dlg                     1229
#define opt_misc_dlg                    1230
#define filesize_dlg                    1231
#define inpfile_dlg                     1232
#define inpfolder_dlg                   1233
#define folder_notify_dlg               1234
#define main_comment_dlg                1235
#define patset_system_dlg               1236
#define countdown_dlg                   1237
#define patset_dst_dlg                  1238
#define patset_timer_dlg                1239
#define patset_adv_dlg                  1240
#define path_convert_dlg                1241
#define overwrite_notify_dlg            1242
#define del_pat_notify_dlg1             1243
#define log_err_notify_dlg              1244
#define patset_ign2_dlg                 1245
#define PATSET_DST_COMMENT              1246
#define FILEOPENORD                     1536
#define MENU_EXIT                       40001
#define MENU_FILE_EXIT                  40002
#define MENU_HELP_CONTENT               40003
#define MENU_HELP_ABOUT                 40004
#define MENU_SETENV                     40005
#define MENU_BACKUP                     40006
#define MENU_REGINIT                    40007
#define MENU_FILESIZE                   40008
#define MENU_START_NAME                 40009
#define MENU_START_ALL                  40010
#define MENU_OPEN                       40011
#define MENU_QUICK_BACKUP               40012
#define ID_40015                        40013
#define MENU_ERROR_LOG                  40014
#define MENU_REGSAVE                    40015
#define MENU_REGLOAD                    40016

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         40017
#define _APS_NEXT_CONTROL_VALUE         1247
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
